name: Docs Linter

on:
  # Triggers the workflow on push or pull request events but
  # only for the default branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run markdown linter
        run: |
          npm install
          npm test
      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - name: Check SUMMARY.md
        run: |
          python .github/scripts/check_summary.py src
